name: Build and Push to DOCR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install doctl
        # Uses the official DigitalOcean GitHub Action
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry
        # Authenticates Docker using doctl
        run: doctl registry login --expiry-seconds 600

      - name: Set SHORT_SHA env variable
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build container image
        run: |
          docker build \
            -t ${{ secrets.REGISTRY_NAME }}/adenacenter:${{ env.SHORT_SHA }} \
            -t ${{ secrets.REGISTRY_NAME }}/adenacenter:latest \
            .

      - name: Push image to DigitalOcean Container Registry
        run: docker push -a ${{ secrets.REGISTRY_NAME }}/adenacenter

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@${{ secrets.VPS_IP }}:22/adenacenter-dev'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          deploy_docker_image: ${{ secrets.REGISTRY_NAME }}/adenacenter:${{ env.SHORT_SHA }}